"""Reader questions mapped one-to-one to preserved technical source pages."""
QUESTIONS = {
1: [
    'Why does the serial loop sample only one input value?',
    'Why do seven nonblocking increments not advance seven cycles?',
    'When does a loop repeat hardware rather than time?',
    'What did the loop simulation actually demonstrate?',
    'Should I capture a serial bit by index or by shifting?',
    'How do eight clock edges reconstruct the byte?',
    'How do the three serial-receiver exercises connect?',
    'What should I check when a serial receiver fails?',
    'How do start, stop and missing-stop recovery work?',
    'When should the receiver check odd parity?',
],
2: [
    'Which saved questions are answered in this review?',
    'When do I need genvar and elaboration?',
    'Can either loop style reverse a vector?',
    'Why is the carry chain a wire rather than stored state?',
    'Why can initial not maintain a live population count?',
    'Why use bitwise operators, and how do mux selectors divide work?',
    'Why does the Lemmings counter not need another reset?',
    'What do the reset, wiring and storage examples establish?',
    'What is the difference between ~ and !?',
    'Why do & and && happen to agree with this mask?',
    'Why does an incomplete assignment intentionally create a latch?',
],
3: [
    'Which HDLC patterns must be reported, and when?',
    'How do Moore and Mealy outputs differ at a sampling edge?',
    'Why does the first Mealy attempt report the wrong cycle?',
    'How should flag and error behave on a continuous stream?',
    'Why did using reg not prevent Mealy-style output behavior?',
    'Why is the first Moore rewrite still early?',
    'Why does the working Moore machine use ten states?',
    'How does the working FSM keep processing incoming bits?',
    'What do the discard, flag and error traces show?',
    'When do nonblocking updates and reset become visible?',
    'Which details in the HDLC code deserve a second check?',
    'What did the reference-model verification cover?',
    'What exactly was written in the first attempt?',
    'How are the working states and transitions coded?',
    'How are the remaining transitions and outputs coded?',
],
4: [
    'Why can water-level inputs not replace FSM history?',
    'Does edge detection compare two consecutive clock samples?',
    'Why is asynchronous reset in the sensitivity list?',
    'How do reduction, bitwise and logical operators differ?',
    'Which recovered examples were checked, and how?',
],
5: [
    'What do +: and -: mean in an indexed part-select?',
    'How do I check byte slices and derive a D-input equation?',
    'Why must a clocked PS/2 data register hold unmatched bytes?',
    'How do the complete parser and datapath fit together?',
    'On which edge are all three bytes and done valid?',
],
6: [
    "Why is LSB-first two's complement copy-then-invert?",
    'Why does the Moore complementer need three states?',
    'What does every state transition remember?',
    'What changes after each clock edge and asynchronous reset?',
    'How does each part of the original source implement the rule?',
    'How do clearer state names and a Mealy version compare?',
    'Which mistakes and test cases distinguish the solutions?',
],
7: [
    'Which earlier questions are kept with the Day 5 review?',
    'Why preserve direction history and the previous input sample?',
    'How do reset events and operator classes affect this code?',
    'Why are OR and the two concatenation padding bits needed?',
    'How do sticky capture, ring/vibrate and one-hot state work?',
    'What remained to check in one-hot encoding and the follow-up?',
    'Which corrected examples passed the local self-check?',
    'What did the historical submission checkpoint record?',
    'Which further submissions appear in the saved evidence?',
    'How do the historical records connect to the question notes?',
    'What do the last records prove, and what is historical only?',
],
8: [
    'Which questions need simulation and which need FPGA reasoning?',
    'Why can OR not select the newest dual-edge sample?',
    'How does the clock level select the newest stored value?',
    'Why can simulated dual-edge behavior differ from FPGA hardware?',
    'Why is ordinary FPGA fabric not a dual-edge flip-flop?',
    'When do I use dedicated DDR input or output resources?',
    'How does the AMD/Xilinx IDDR example sample the input?',
    'How does the AMD/Xilinx ODDR example drive the output?',
    'What do Intel DDIO and the timing constraints contribute?',
    'Which architecture fits internal logic versus an I/O interface?',
    'Why is only half a clock period available on some paths?',
    'Where do glitches, reset and startup matter?',
    'How does the XOR-feedback alternative work?',
    'How do I infer Circuit5 from its waveform?',
    'How do the selector values become a case statement?',
    'How can I check a waveform-derived circuit systematically?',
    'What verification and primary sources support the explanation?',
    'What should I remember before using dual-edge logic?',
],
9: [
    'When does the first of the three samples occur?',
    'How should I number sample edges from zero?',
    'Why does a loop not collect three future samples?',
    'Why did the three-state attempt lose the intended timing?',
    'What causes the count error and the unwanted gap cycle?',
    'Why was count plus w still wrong in the earlier attempt?',
    'Why must the third decision include the current input?',
    'When do defaults assign a value, and when do registers hold?',
    'What does the complete corrected RTL look like?',
    'Do all eight three-bit groups produce the correct result?',
    'Which boundary checks should I repeat for this FSM?',
],
10: [
    'What does the width warning mean in the problem map?',
    'How do I derive Y0 and z from the FSM?',
    'How do I derive the next-state bit Y2?',
    'How do load, enable and data connect to the counter?',
    'How do the related module and counter examples compare?',
    'What should I check before accepting the FSM equations?',
],
11: [
    'Why can this continuously driven wire not be a reg initializer?',
    'How does the carry connection propagate through the adder?',
    'Why does reset belong in the shift-register storage block?',
    'Which old values and assignment priority govern the BCD clock?',
    'How do the complete BCD rollovers and boundaries work?',
],
12: [
    'Why must combinational outputs be assigned on every path?',
    'How does the missing else retain the previous value?',
    'Can a default or Boolean expression remove the latch?',
    'How should I write the complete 1101 recognizer?',
    'Why do overlap handling and sticky detection need five states?',
],
13: [
    'Why does the K-map expression use | instead of +?',
    'Why can + appear to work for this particular expression?',
    'What are SOP, POS and De Morgan\'s law?',
    'How do I apply SOP and POS to the actual problem?',
    'Why must a whole Rule 90 generation change together?',
    'Why did I use nextVal, and is it required?',
    'How does Rule 110 use left, center and right cells?',
    'Why does the Rule 110 expression match the truth table?',
],
14: [
    'How do the six timer-series exercises fit together?',
    'Why does counting 0 through 999 give 1000 cycles?',
    'Why does MSB-first input still shift toward the MSB?',
    'What happens when shift and count enables are both true?',
    'Why is the 1101 question repeated in the timer series?',
    'How do I get four capture cycles without multiple drivers?',
    'How do search, capture, count, notify and acknowledge connect?',
    'Why must the capture counter be reset for another transaction?',
    'What do state and next_state mean just before an edge?',
    'When should the clocked block inspect state, next_state or both?',
    'Why does the fourth captured bit need old delay plus current data?',
    'How do nested counters implement (delay + 1) x 1000 cycles?',
    'How is the complete controller and next-state logic written?',
    'How do the final datapath, outputs and boundary checks fit?',
],
15: [
    'What common method solves all three LFSR exercises?',
    'How is an LFSR a state machine written as bit equations?',
    'Why does tap position k become Verilog index k-1?',
    'Why is q[2] assigned after the whole five-bit vector?',
    'How do old values produce the 31-state cycle?',
    'How do I translate the Mt2015 schematic into D-input equations?',
    'Why does parallel load take priority over feedback?',
    'How does the three-bit circuit visit all seven nonzero states?',
    'How do I scale the five-bit pattern to the 32-bit taps?',
    'Why do the XORs read old q rather than a partly shifted q?',
    'Which equations, seed and first transition should I verify?',
],
16: [
    'Why is a Conway cell at row * 16 + col?',
    'How do row and column boundaries wrap independently?',
    'Why must every neighbor come from the old generation?',
    'How do load and the complete Conway implementation work?',
    'Why do nested loops not take 256 clock cycles?',
    'How do I trace a boundary and test the whole grid?',
],
0: [
    'What is an LFSR, and what do seed, tap, period and lockup mean?',
    'How do feedback forms and tap choices determine the period?',
    'Where are LFSRs useful, and how should I code their state?',
],
}

CHAPTER_QUESTIONS = {
1:'How do real clock edges receive a complete serial frame?',
2:'How do loops, muxes and operators describe hardware?',
3:'Why do the HDLC patterns appear in the wrong output cycle?',
4:'What do the recovered state, edge and operator questions mean?',
5:'How do byte slices and PS/2 packet storage work?',
6:"Why does serial two's complement need these Moore states?",
7:'Which small RTL mistakes explain the saved submissions?',
8:'How do I reason about dual-edge samples and FPGA hardware?',
9:'How do I use three samples without inserting a gap?',
10:'How do I resolve FSM widths and counter connections?',
11:'When do wire, reg and reset describe the right hardware?',
12:'Why do assignments infer latches or clocked state?',
13:'How do Boolean forms connect to Rules 90 and 110?',
14:'How do I build the timer and use state versus next_state?',
15:'How do I translate all three LFSRs into correct RTL?',
16:'How do indexing, wraparound and next state implement Conway?',
0:'What LFSR definitions and limits should I remember?',
}
